title: "Ibrahim Hossain Sajal"
description: "Statistical Genetics | Genomics | R | Biostatistics"
baseurl: ""            # keep empty for user sites
url: "https://ihsajal.github.io"

author:
  name: "Ibrahim Hossain Sajal"
  desc: ""
  email: "sajali2@nih.gov"
  selfie: "/assets/img/Photo_IbrahimHossainSajal_Github.jpg"   

social:
  email: true
  github: "ihsajal"
  linkedin: "https://www.linkedin.com/in/ihsajal"
  default_txt: "Follow"

nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
