title: "Ibrahim Hossain Sajal"
description: "Statistical Genetics | Genomics | R | Biostatistics"
baseurl: ""            # keep empty for user sites
url: "https://ihsajal.github.io"

author:
  name: "Ibrahim Hossain Sajal"
  desc: "A Biostatistician with a PhD in Data Science and Statistics and currently working in Cancer Epidemiology and Genetics at the National Cancer Institute"
  email: "sajali2@nih.gov"
  selfie: "/assets/img/Photo_IbrahimHossainSajal_Github.jpg"   

social:
  email: true
  github: "ihsajal"
  linkedin: "https://www.linkedin.com/in/ihsajal"
  default_txt: "Follow"
